# Generated by Django 3.0.7 on 2021-01-16 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20210116_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=200, verbose_name='Author ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('writing_level', models.IntegerField(verbose_name='Writing Level')),
                ('publisher_id', models.CharField(max_length=200, verbose_name='Publisher ID')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=200, verbose_name='ISBN')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('summary', models.TextField(verbose_name='Plot')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Author')),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
        ),
    ]
