# Generated by Django 3.0.7 on 2021-01-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_author_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_id', models.CharField(max_length=200, verbose_name='Publication ID')),
                ('release_no', models.CharField(max_length=200, verbose_name='Release No')),
                ('isbn', models.CharField(max_length=200, verbose_name='ISBN')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('publication_remarks', models.TextField(verbose_name='Remarks')),
            ],
            options={
                'verbose_name_plural': 'Publications',
            },
        ),
    ]
