# Generated by Django 3.0.7 on 2021-01-16 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_publication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='publication_id',
        ),
    ]
