# Generated by Django 3.0.7 on 2021-01-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_publication_publication_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['position'], 'verbose_name_plural': 'Books'},
        ),
        migrations.AddField(
            model_name='book',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Position'),
        ),
    ]
