# Generated by Django 3.0.7 on 2021-01-17 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210117_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': 'Books'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='position',
        ),
    ]
