# Generated by Django 3.1.5 on 2021-07-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210117_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='series',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6')], default='A1', max_length=2),
        ),
    ]
