# Generated by Django 3.1.5 on 2021-09-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210718_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['my_order'], 'verbose_name_plural': 'Publications'},
        ),
        migrations.AddField(
            model_name='publication',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publication',
            name='series',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3')], max_length=2),
        ),
    ]
