# Generated by Django 3.1.5 on 2021-09-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210901_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['my_order'], 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name_plural': 'Publications'},
        ),
        migrations.RemoveField(
            model_name='publication',
            name='my_order',
        ),
        migrations.AddField(
            model_name='book',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
