# Generated by Django 3.1.5 on 2021-09-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210901_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['priority_no'], 'verbose_name_plural': 'Publications'},
        ),
        migrations.AddField(
            model_name='publication',
            name='priority_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
