# Generated by Django 3.2.7 on 2021-09-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210929_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='book_title',
            field=models.CharField(max_length=200, verbose_name='Book Title'),
        ),
    ]
